/**
 * Generates a comprehensive migration report from the Datadog to Checkly migration.
 *
 * Reads all exported and converted JSON files to produce:
 *   - exports/migration-report.json (machine-readable)
 *   - exports/migration-report.md (human-readable)
 *   - migration-mapping.csv (Datadog-to-Checkly ID mapping)
 *
 * The report includes:
 *   - Summary of what was converted
 *   - What was NOT converted (and why)
 *   - Private locations that need to be created in Checkly
 *   - Environment variables that need values
 *   - Concrete next steps for the migration team
 */

import { readFile, writeFile, readdir } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { getOutputRoot, getExportsDir } from './shared/output-config.ts';
import { uniqueLogicalId, sanitizeFilename } from './shared/utils.ts';
import { readJsonFileSafe } from './shared/fs-json.ts';
import type { MigrationFlag, MigrationFlagsFile } from './shared/migration-flags.ts';

let EXPORTS_DIR = '';
let CHECKLY_DIR = '';

// Input files - initialized in main() after CHECKLY_DIR is set
let FILES: {
  exportSummary: string;
  privateLocations: string;
  apiTests: string;
  apiChecks: string;
  multiStepTests: string;
  browserTests: string;
  envVariables: string;
  secrets: string;
  variableUsage: string;
  ddTestStatus: string;
  missingSecretsReport: string;
  migrationFlags: string;
  browserManifestPublic: string;
  browserManifestPrivate: string;
  multiManifestPublic: string;
  multiManifestPrivate: string;
};

// Output files - initialized in main() after CHECKLY_DIR is set
let OUTPUT_JSON = '';
let OUTPUT_MD = '';
let OUTPUT_CSV = '';

// Types for the input data
interface ExportSummary {
  exportedAt: string;
  site: string;
  summary: {
    apiTests: number;
    browserTests: number;
    globalVariables: number;
    privateLocations: number;
    publicLocations: number;
    unmappedLocations: number;
  };
}

interface PrivateLocation {
  datadogId: string;
  checklySlug: string;
  name?: string;
  usageCount: number;
  source: string;
}

interface PrivateLocationsFile {
  exportedAt: string;
  site: string;
  count: number;
  locations: PrivateLocation[];
}

interface ApiChecksFile {
  convertedAt: string;
  source: { exportedAt: string; site: string };
  summary: {
    total: number;
    converted: number;
    successful: number;
    failed: number;
    skippedMultiStep: number;
    skippedNonHttp: number;
  };
  skippedNonHttpTests: Record<string, Array<{ public_id: string; name: string }>>;
  privateLocationsFound: string[];
  checks: Array<{
    logicalId: string;
    name: string;
    locations?: string[];
    privateLocations?: string[];
    originalLocations?: string[];
    tags?: string[];
    hasCertificate?: boolean;
    request?: {
      certificate?: {
        key?: { filename?: string };
        cert?: { filename?: string };
      };
    };
    _conversionError?: string;
  }>;
}

interface MultiStepTestsFile {
  exportedAt: string;
  site: string;
  count: number;
  tests: Array<{
    public_id: string;
    name: string;
    locations?: string[];
    privateLocations?: string[];
    originalLocations?: string[];
    tags?: string[];
    hasCertificate?: boolean;
    _promotionReason?: string;
    config?: {
      steps?: Array<{
        request?: {
          certificate?: {
            key?: { filename?: string };
            cert?: { filename?: string };
          };
        };
      }>;
    };
  }>;
}

interface BrowserTestsFile {
  exportedAt: string;
  site: string;
  count: number;
  tests: Array<{
    public_id: string;
    name: string;
    locations?: string[];
    privateLocations?: string[];
    originalLocations?: string[];
    // options.device_ids (never config.device_ids; plan 10-01): the raw Datadog
    // browser device profiles. Cross-referenced by public_id in main() to surface
    // D-04's declared-vs-distinct browser count in the PWCS report section.
    options?: { device_ids?: string[] };
  }>;
}

// Raw Datadog API tests file (output of step 01, contains all subtypes incl. tcp).
// Used to count TCP monitors that will be generated by step 04b.
interface RawApiTestsFile {
  exportedAt: string;
  site: string;
  count: number;
  tests: Array<{
    public_id: string;
    name: string;
    subtype?: string;
    locations?: string[];
    privateLocations?: string[];
    originalLocations?: string[];
    config?: { request?: { host?: string; port?: number } };
  }>;
}

interface Variable {
  key: string;
  value: string;
  locked: boolean;
}

interface VariableUsageEntry {
  usageCount: number;
  checks: string[];
}

interface VariableUsageFile {
  generatedAt: string;
  totalVariablesReferenced: number;
  variables: Record<string, VariableUsageEntry>;
}

interface Manifest {
  generatedAt: string;
  outputDir: string;
  locationType: string;
  // hasMultiCandidate is written by src/07 (plan 08-03) when a browser spec
  // resolved at least one step with two or more firstMatch candidates. Optional
  // and null-tolerant: manifests predating the field behave as false.
  // pwEngines is written by src/07 (plan 10-02), the deduped canonical-order
  // Playwright engine list; length > 1 means this check emitted as a
  // PlaywrightCheck (plan 10-03). Optional and null-tolerant, same as above.
  files: Array<{ logicalId: string; name: string; filename: string; hasMultiCandidate?: boolean; pwEngines?: string[] }>;
  skipped?: Array<{ logicalId: string; name: string; reason?: string }>;
}

interface MissingSecretsReportFile {
  generatedAt: string;
  totalSecrets: number;
  secretsWithEmptyValues: number;
  checksAffected: number;
  filesModified: number;
  filesSkipped: number;
  errors: number;
  affectedChecks: Array<{
    checkName: string;
    missingSecrets: string[];
  }>;
}

interface DdStatusCounts {
  total: number;
  passing: number;
  failing: number;
  noData: number;
  unknown: number;
  deactivated: number;
}

interface DdTestStatusFile {
  fetchedAt: string;
  site: string;
  summary: DdStatusCounts;
  publicSummary: DdStatusCounts;
  privateSummary: DdStatusCounts;
  tests: Array<{
    publicId: string;
    name: string;
    monitorId: number | null;
    overallState: string;
    isDeactivated: boolean;
    tag: string | null;
    locationType: 'public' | 'private';
    fetchedAt: string;
  }>;
}

// Report structure
interface MigrationReport {
  generatedAt: string;
  source: {
    exportedAt: string;
    site: string;
  };
  summary: {
    totalDatadogTests: number;
    totalChecklyChecks: number;
    conversionRate: string;
  };
  converted: {
    apiChecks: { public: number; private: number; total: number };
    browserChecks: { public: number; private: number; total: number };
    multiStepChecks: { public: number; private: number; total: number };
    tcpMonitors: { public: number; private: number; total: number };
    dnsMonitors: { public: number; private: number; total: number };
  };
  notConverted: {
    nonHttpTests: {
      count: number;
      byType: Record<string, Array<{ publicId: string; name: string }>>;
    };
    failedConversions: {
      count: number;
      tests: Array<{ publicId: string; name: string; reason: string }>;
    };
    skippedFromManifests: Array<{ publicId: string; name: string; reason: string }>;
  };
  variables: {
    total: number;
    nonSecure: number;
    secureNeedingValues: number;
    secretKeys: string[];
    usage: {
      totalReferenced: number;
      byVariable: Record<string, { usageCount: number; checks: string[] }>;
    };
  };
  privateLocations: {
    count: number;
    locations: Array<{
      checklySlug: string;
      usageCount: number;
      datadogId: string;
    }>;
  };
  datadogStatus?: {
    checkedAt: string;
    summary: DdStatusCounts;
    publicSummary: DdStatusCounts;
    privateSummary: DdStatusCounts;
    deactivatedTests: Array<{
      publicId: string;
      name: string;
      reason: string;
      locationType: string;
      tag: string | null;
    }>;
    reviewTests: Array<{
      publicId: string;
      name: string;
      tag: string;
      locationType: string;
    }>;
  };
  missingSecrets?: {
    checkedAt: string;
    checksAffected: number;
    filesModified: number;
    affectedChecks: Array<{
      checkName: string;
      missingSecrets: string[];
    }>;
  };
  checkLevelSecrets?: {
    totalEntries: number;
    uniqueChecks: number;
    entries: Array<{ checkName: string; key: string }>;
  };
  clientCertificates?: {
    totalChecks: number;
    checks: Array<{
      checkName: string;
      checkType: 'api' | 'multistep';
      publicId: string;
      certFiles: { key?: string; cert?: string };
    }>;
  };
  promotions?: Array<{
    publicId: string;
    name: string;
    reason: string;
    locationType: 'public' | 'private';
  }>;
  // Migration flags (FLAG-03): the shared MigrationFlag record from the 07-01
  // cross-phase contract is the single source of truth, so the report surface and
  // the emitter cannot drift. Present only when at least one flag exists.
  migrationFlags?: MigrationFlag[];
  // Self-healing locator chains (D-06): the browser checks whose specs emitted a
  // multi-candidate firstMatch fallback chain (manifest hasMultiCandidate true).
  // Derived from the browser manifests in main(); present only when the count is
  // positive. Drives the Self-Healing Locator Chains report section.
  multiSelector?: {
    count: number;
    checks: Array<{ publicId: string; name: string; locationType: 'public' | 'private' }>;
  };
  // Playwright Check Suites (PWCS-03): the browser checks whose manifests carry a
  // multi-engine pwEngines list (length > 1), so src/08 emitted a PlaywrightCheck
  // rather than a BrowserCheck. Derived from the browser manifests' pwEngines field
  // in main(); present only when the count is positive. declaredBrowserCount and
  // distinctEngineCount surface D-04's coverage-reduction visibility (how many
  // Datadog browser device profiles collapsed to how many distinct Playwright
  // engine projects); hasPrivateLocationCaveat marks a check needing the D-07
  // Checkly Agent version verification. Drives the Playwright Check Suites
  // (Multi-Browser) report section.
  playwrightCheckSuites?: {
    count: number;
    checks: Array<{
      publicId: string;
      name: string;
      locationType: 'public' | 'private';
      declaredBrowserCount: number;
      distinctEngineCount: number;
      hasPrivateLocationCaveat: boolean;
    }>;
  };
  nextSteps: string[];
}

// The runtime exhaustion token emitted into generated specs by src/07
// (LOCATOR_EXHAUSTION_TOKEN). Duplicated here as a documentation constant so the
// report copy names the exact greppable string without importing the whole
// src/07 spec generator. Keep the two in sync (both are fixed literals).
const LOCATOR_EXHAUSTION_TOKEN = 'MIGRATION-LOCATOR-EXHAUSTION';

/**
 * Safely read and parse a JSON file, returning null if it doesn't exist.
 *
 * Thin re-export of the shared canonical reader (src/shared/fs-json.ts), kept
 * under the historical readJsonFile name so this step's many call sites and the
 * exported surface stay byte-neutral (IN-01: one source of truth, two consumers).
 */
export const readJsonFile = readJsonFileSafe;

/**
 * Project the raw dd-test-status tests into the report's deactivated and review
 * lists, keeping the two mutually exclusive.
 *
 * A No Data check with an absent/unknown config status is BOTH deactivated
 * (activated: false) AND tagged reviewNoDataInDatadog (D-06). It must surface
 * only in the deactivated list, never under "Checks Left Active for Review",
 * which asserts the check is still running. The review list is therefore
 * restricted to genuinely-active review checks (the STAT-01 live case) via the
 * !isDeactivated guard; deactivated review-tagged checks fall through to the
 * deactivated list, which carries the tag so it can be grouped by its true tag.
 *
 * @param tests - The dd-test-status.json tests array.
 * @returns The deactivated and review projections used by the report.
 */
export function projectDatadogStatusTests(
  tests: DdTestStatusFile['tests'],
): {
  deactivatedTests: Array<{
    publicId: string;
    name: string;
    reason: string;
    locationType: string;
    tag: string | null;
  }>;
  reviewTests: Array<{
    publicId: string;
    name: string;
    tag: string;
    locationType: string;
  }>;
} {
  return {
    deactivatedTests: tests
      .filter(t => t.isDeactivated)
      .map(t => ({
        publicId: t.publicId,
        name: t.name,
        reason: t.overallState,
        locationType: t.locationType,
        tag: t.tag,
      })),
    // Checks left active but flagged for human review (any review* tag). The
    // !isDeactivated guard keeps deactivated absent-status No Data checks out of
    // this list (D-06); grouping downstream is by the tag string itself, so
    // future review tags (e.g. reviewAI in milestone 2) flow through unchanged.
    reviewTests: tests
      .filter(t => t.tag !== null && t.tag.startsWith('review') && !t.isDeactivated)
      .map(t => ({
        publicId: t.publicId,
        name: t.name,
        tag: t.tag as string,
        locationType: t.locationType,
      })),
  };
}

/**
 * Generate the markdown report
 */
export function generateMarkdownReport(report: MigrationReport): string {
  const lines: string[] = [];

  lines.push('# Datadog to Checkly Migration Report');
  lines.push('');
  lines.push(`**Generated:** ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push(`**Source:** ${report.source.site}`);
  lines.push(`**Export Date:** ${new Date(report.source.exportedAt).toLocaleString()}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Datadog Synthetics:** ${report.summary.totalDatadogTests.toLocaleString()}`);
  lines.push(`- **Checkly Checks Created:** ${report.summary.totalChecklyChecks.toLocaleString()}`);
  lines.push(`- **Conversion Rate:** ${report.summary.conversionRate}`);
  lines.push('');

  // What was migrated
  lines.push('## What Was Migrated');
  lines.push('');
  lines.push('| Check Type | Public | Private | Total |');
  lines.push('|------------|--------|---------|-------|');
  lines.push(`| API Checks | ${report.converted.apiChecks.public} | ${report.converted.apiChecks.private} | ${report.converted.apiChecks.total} |`);
  lines.push(`| Browser Checks | ${report.converted.browserChecks.public} | ${report.converted.browserChecks.private} | ${report.converted.browserChecks.total} |`);
  lines.push(`| Multi-Step Checks | ${report.converted.multiStepChecks.public} | ${report.converted.multiStepChecks.private} | ${report.converted.multiStepChecks.total} |`);
  lines.push(`| TCP Monitors | ${report.converted.tcpMonitors.public} | ${report.converted.tcpMonitors.private} | ${report.converted.tcpMonitors.total} |`);
  lines.push(`| DNS Monitors | ${report.converted.dnsMonitors.public} | ${report.converted.dnsMonitors.private} | ${report.converted.dnsMonitors.total} |`);
  lines.push('');

  // What was NOT migrated
  if (report.notConverted.nonHttpTests.count > 0 || report.notConverted.failedConversions.count > 0) {
    lines.push('## What Was NOT Migrated');
    lines.push('');

    if (report.notConverted.nonHttpTests.count > 0) {
      lines.push(`### Non-HTTP Tests (${report.notConverted.nonHttpTests.count} tests)`);
      lines.push('');
      lines.push('Checkly does not yet support SSL/ICMP synthetics. These were skipped:');
      lines.push('(TCP and DNS tests are now migrated as TcpMonitor / DnsMonitor constructs — see "What Was Migrated".)');
      lines.push('');
      for (const [type, tests] of Object.entries(report.notConverted.nonHttpTests.byType)) {
        lines.push(`#### ${type.toUpperCase()} (${tests.length})`);
        lines.push('');
        for (const test of tests) {
          lines.push(`- \`${test.publicId}\` — ${test.name}`);
        }
        lines.push('');
      }
    }

    if (report.notConverted.failedConversions.count > 0) {
      lines.push(`### Failed Conversions (${report.notConverted.failedConversions.count} tests)`);
      lines.push('');
      lines.push('These tests could not be converted:');
      lines.push('');
      for (const test of report.notConverted.failedConversions.tests) {
        lines.push(`- \`${test.publicId}\` — ${test.name} (**${test.reason}**)`);
      }
      lines.push('');
      lines.push('> **Note:** Tests with unsupported HTTP methods (like OPTIONS) are skipped entirely.');
      lines.push('> Tests with JavaScript assertions are converted but without those assertions - review and add equivalent Playwright assertions manually.');
      lines.push('');
    }

    if (report.notConverted.skippedFromManifests.length > 0) {
      lines.push(`### Skipped Multi-Step/Browser Tests (${report.notConverted.skippedFromManifests.length} tests)`);
      lines.push('');
      lines.push('These tests were skipped during spec generation:');
      lines.push('');
      for (const test of report.notConverted.skippedFromManifests) {
        lines.push(`- \`${test.publicId}\` — ${test.name} (**${test.reason}**)`);
      }
      lines.push('');
    }
  }

  // Datadog Test Status at Migration Time
  if (report.datadogStatus) {
    const ds = report.datadogStatus;
    lines.push('## Datadog Test Status at Migration Time');
    lines.push('');
    lines.push(`**Checked at:** ${new Date(ds.checkedAt).toLocaleString()}`);
    lines.push('');
    lines.push('| Status | Public | Private | Total |');
    lines.push('|--------|--------|---------|-------|');
    lines.push(`| Passing (OK) | ${ds.publicSummary.passing} | ${ds.privateSummary.passing} | ${ds.summary.passing} |`);
    lines.push(`| Failing (Alert) | ${ds.publicSummary.failing} | ${ds.privateSummary.failing} | ${ds.summary.failing} |`);
    lines.push(`| No Data | ${ds.publicSummary.noData} | ${ds.privateSummary.noData} | ${ds.summary.noData} |`);
    lines.push(`| Unknown | ${ds.publicSummary.unknown} | ${ds.privateSummary.unknown} | ${ds.summary.unknown} |`);
    lines.push(`| **Total** | **${ds.publicSummary.total}** | **${ds.privateSummary.total}** | **${ds.summary.total}** |`);
    lines.push(`| **Deactivated** | **${ds.publicSummary.deactivated}** | **${ds.privateSummary.deactivated}** | **${ds.summary.deactivated}** |`);
    lines.push('');

    if (ds.deactivatedTests.length > 0) {
      const failingTests = ds.deactivatedTests.filter(t => t.reason === 'Alert');
      const noDataTests = ds.deactivatedTests.filter(t => t.reason === 'No Data');

      if (failingTests.length > 0) {
        lines.push(`### Failing Tests (${failingTests.length} — tagged \`failingInDatadog\`)`);
        lines.push('');
        const display = failingTests.slice(0, 25);
        for (const test of display) {
          lines.push(`- \`${test.publicId}\` [${test.locationType}] — ${test.name}`);
        }
        if (failingTests.length > 25) {
          lines.push(`- ... and ${failingTests.length - 25} more`);
        }
        lines.push('');
      }

      if (noDataTests.length > 0) {
        // Deactivated No Data checks carry two distinct tags: paused checks
        // (noDataInDatadog, D-04 row 2) and absent-status checks
        // (reviewNoDataInDatadog, D-06). Group by the actual tag so each bullet
        // sits under its true tag and a grep by tag finds every check.
        const noDataByTag = new Map<string, typeof noDataTests>();
        for (const test of noDataTests) {
          const key = test.tag ?? 'noDataInDatadog';
          const bucket = noDataByTag.get(key) ?? [];
          bucket.push(test);
          noDataByTag.set(key, bucket);
        }
        for (const [tag, tagged] of noDataByTag) {
          lines.push(`### No Data Tests (${tagged.length}, tagged \`${tag}\`)`);
          lines.push('');
          const display = tagged.slice(0, 25);
          for (const test of display) {
            lines.push(`- \`${test.publicId}\` [${test.locationType}]: ${test.name}`);
          }
          if (tagged.length > 25) {
            lines.push(`- ... and ${tagged.length - 25} more (see dd-test-status.json)`);
          }
          lines.push('');
        }
      }

      lines.push('> **Action:** Review deactivated checks. Fix failing tests or re-activate paused tests as needed.');
      lines.push('');
    }
  }

  // Checks Left Active for Review (D-09/D-10)
  // Grouped by the review tag string itself, so any new review* tag auto-appears
  // as its own subsection with no tag-to-heading map to maintain.
  if (report.datadogStatus && report.datadogStatus.reviewTests.length > 0) {
    const reviewTests = report.datadogStatus.reviewTests;
    lines.push('## Checks Left Active for Review');
    lines.push('');
    lines.push(`**${reviewTests.length} check(s)** were left active but flagged for human review.`);
    lines.push('These checks kept their Datadog activation and carry a `review*` tag so you can verify them.');
    lines.push('');
    for (const tag of new Set(reviewTests.map(t => t.tag))) {
      const tagged = reviewTests.filter(t => t.tag === tag);
      lines.push(`### ${tag} (${tagged.length})`);
      lines.push('');
      const display = tagged.slice(0, 25);
      for (const test of display) {
        lines.push(`- \`${test.publicId}\` [${test.locationType}]: ${test.name}`);
      }
      if (tagged.length > 25) {
        lines.push(`- ... and ${tagged.length - 25} more (see dd-test-status.json)`);
      }
      lines.push('');
    }
    lines.push('> **Action:** These were live in Datadog but monitor/search reported No Data, so they were left active rather than deactivated. Verify recent run health in Datadog and remove the review tag once confirmed.');
    lines.push('');
  }

  // Promoted Checks (REGX-09)
  // Grouped by the promotion reason string itself, so any new reason auto-appears
  // as its own subsection with no reason lookup map to maintain (mirrors the
  // review section above). Sourced from the _promotionReason field, never .check.ts.
  if (report.promotions && report.promotions.length > 0) {
    const promotions = report.promotions;
    lines.push('## Promoted Checks');
    lines.push('');
    lines.push(`**${promotions.length} check(s)** were promoted from an API Check to a MultiStepCheck to preserve assertions a plain API Check cannot express.`);
    lines.push('These checks carry a `promotedFromApiCheck` tag and run as one-step Playwright specs.');
    lines.push('');
    for (const reason of new Set(promotions.map(p => p.reason))) {
      const grouped = promotions.filter(p => p.reason === reason);
      lines.push(`### ${reason} (${grouped.length})`);
      lines.push('');
      const display = grouped.slice(0, 25);
      for (const p of display) {
        lines.push(`- \`${p.publicId}\` [${p.locationType}]: ${p.name}`);
      }
      if (grouped.length > 25) {
        lines.push(`- ... and ${grouped.length - 25} more (see multi-step-tests.json)`);
      }
      lines.push('');
    }
    lines.push('> **Action:** Regex assertions were promoted to MultiStepChecks so they assert with native RegExp. Verify each promoted spec replays the original request faithfully, then activate as usual.');
    lines.push('');
  }

  // Migration Flags (FLAG-03)
  // Sourced only from exports/migration-flags.json (via report.migrationFlags),
  // never by re-scanning the generated .spec.ts files. Grouped by the reason
  // string itself, so new FlagReason codes added by Phases 8/9/10 auto-appear as
  // their own subsections with no lookup map to maintain (mirrors the Promoted
  // Checks and review sections above).
  if (report.migrationFlags && report.migrationFlags.length > 0) {
    const flags = report.migrationFlags;
    lines.push('## Migration Flags');
    lines.push('');
    lines.push(`**${flags.length} flag(s)** mark points where the generator could not close a gap deterministically.`);
    lines.push('Each flagged check carries a `reviewMigrationFlag` tag; checks flagged `locator-unresolvable` are additionally deactivated (`activated: false`).');
    lines.push('');
    for (const reason of new Set(flags.map(f => f.reason))) {
      const grouped = flags.filter(f => f.reason === reason);
      lines.push(`### ${reason} (${grouped.length})`);
      lines.push('');
      const display = grouped.slice(0, 25);
      for (const f of display) {
        const stepSuffix = f.stepIndex === null ? '' : ` step ${f.stepIndex + 1}`;
        lines.push(`- \`${f.publicId}\`${stepSuffix}: ${f.message}`);
      }
      if (grouped.length > 25) {
        lines.push(`- ... and ${grouped.length - 25} more (see migration-flags.json)`);
      }
      lines.push('');
    }
    lines.push('> **Action:** Review each flagged step in its generated spec (grep `// MIGRATION-FLAG:`), fix or replace the flagged residue, then remove the `reviewMigrationFlag` tag and re-activate any deactivated checks.');
    lines.push('');
  }

  // Self-Healing Locator Chains (D-06)
  // Mirrors the Checks Left Active for Review idiom (heading, bold count sentence,
  // per-check bullet list capped at 25, blockquoted Action line). Sourced from the
  // browser manifests' hasMultiCandidate field via report.multiSelector. These
  // checks stay ACTIVE and carry the reviewMultiSelector tag; the section documents
  // the runtime MIGRATION-LOCATOR-EXHAUSTION token so a reviewer knows what to grep
  // for in Checkly run results when every candidate misses at runtime.
  if (report.multiSelector && report.multiSelector.count > 0) {
    const ms = report.multiSelector;
    lines.push('## Self-Healing Locator Chains');
    lines.push('');
    lines.push(`**${ms.count} check(s)** emitted a multi-candidate \`firstMatch()\` fallback chain and are left ACTIVE for review.`);
    lines.push('Each carries a `reviewMultiSelector` tag. The chain tries an ordered list of candidate locators and resolves the first that matches, searching the main page and every iframe, so a check keeps working when one selector shifts.');
    lines.push('');
    lines.push(`When every candidate misses at runtime the spec prints the \`${LOCATOR_EXHAUSTION_TOKEN}\` token to the run log and error group, distinct from an ordinary selector timeout. Grep for it in Checkly run results to find a check whose locators all went stale.`);
    lines.push('');
    const display = ms.checks.slice(0, 25);
    for (const c of display) {
      lines.push(`- \`${c.publicId}\` [${c.locationType}]: ${c.name}`);
    }
    if (ms.checks.length > 25) {
      lines.push(`- ... and ${ms.checks.length - 25} more (see the browser _manifest.json files)`);
    }
    lines.push('');
    lines.push('> **Action:** For each check, verify the element the chain resolved is the one the original Datadog step targeted, then remove the `reviewMultiSelector` tag once confirmed.');
    lines.push('');
  }

  // Playwright Check Suites, multi-browser (PWCS-03)
  // Mirrors the Self-Healing Locator Chains idiom (heading, bold count sentence,
  // per-check bullet capped at 25, blockquoted Action line). Sourced from the
  // browser manifests' pwEngines field via report.playwrightCheckSuites: a check
  // whose test declared more than one browser was emitted as a PlaywrightCheck
  // (never a BrowserCheck) plus a companion playwright.config.ts (plan 10-03). The
  // per-check bullet surfaces D-04's declared-vs-distinct visibility; the D-07
  // caveat clause points to the Migration Flags section for the full text rather
  // than duplicating the flag message (avoids stale-copy drift between surfaces).
  // The two static notes below are gated on the same count > 0 condition so they
  // render exactly once when at least one PlaywrightCheck exists, never per-check.
  if (report.playwrightCheckSuites && report.playwrightCheckSuites.count > 0) {
    const pwcs = report.playwrightCheckSuites;
    lines.push('## Playwright Check Suites (Multi-Browser)');
    lines.push('');
    lines.push(`**${pwcs.count} check(s)** migrated to a Playwright Check Suite (PlaywrightCheck) because Datadog declared more than one browser.`);
    lines.push('Each runs a companion `playwright.config.ts` with one project per distinct Playwright engine, so the migrated check exercises the same browser engines the original Datadog test did.');
    lines.push('');
    const display = pwcs.checks.slice(0, 25);
    for (const c of display) {
      const caveat = c.hasPrivateLocationCaveat
        ? ' (private location: requires Checkly Agent 6.0.3 or newer, see the Migration Flags section)'
        : '';
      lines.push(`- \`${c.publicId}\` [${c.locationType}]: ${c.name} (${c.declaredBrowserCount} declared browser(s) -> ${c.distinctEngineCount} distinct Playwright engine(s))${caveat}`);
    }
    if (pwcs.checks.length > 25) {
      lines.push(`- ... and ${pwcs.checks.length - 25} more (see the browser _manifest.json files)`);
    }
    lines.push('');
    lines.push('> **Action:** After deploy, confirm each Playwright Check Suite runs the intended browser projects (the companion config lists them), then verify the migrated behavior matches the original Datadog browser test.');
    lines.push('');

    lines.push('### Playwright Check Suite entitlement');
    lines.push('');
    lines.push('A PlaywrightCheck requires the `PLAYWRIGHT_NATIVE` entitlement on your Checkly account.');
    lines.push('');
    lines.push('> **Action:** Confirm the entitlement is enabled (run `npx checkly account plan PLAYWRIGHT_NATIVE` or check the Checkly billing page) before deploying any Playwright Check Suite.');
    lines.push('');

    lines.push('### @playwright/test dependency');
    lines.push('');
    lines.push('The generated project declares `@playwright/test` (^1.61.1) as a devDependency because Checkly bundles each Playwright Check Suite from a locally resolvable copy of the package.');
    lines.push('');
    lines.push('> **Action:** Run `npm install` in the generated project directory before `npx checkly test` or `npx checkly deploy` so every Playwright Check Suite bundles successfully.');
    lines.push('');
  }

  // Checks Deactivated Due to Missing Secrets
  if (report.missingSecrets && report.missingSecrets.checksAffected > 0) {
    const ms = report.missingSecrets;
    lines.push('## Checks Deactivated Due to Missing Secrets');
    lines.push('');
    lines.push(`**${ms.checksAffected} check(s)** were deactivated because they reference secret variables with empty values.`);
    lines.push(`These checks are tagged with \`missingSecretsFromDatadog\` and set to \`activated: false\`.`);
    lines.push('');
    lines.push('| Check | Missing Secrets |');
    lines.push('|-------|-----------------|');
    const display = ms.affectedChecks.slice(0, 25);
    for (const ac of display) {
      lines.push(`| ${ac.checkName} | \`${ac.missingSecrets.join('`, `')}\` |`);
    }
    if (ms.affectedChecks.length > 25) {
      lines.push(`| ... | ${ms.affectedChecks.length - 25} more (see missing-secrets-report.json) |`);
    }
    lines.push('');
    lines.push('> **Action:** Fill in secret values in `variables/secrets.json`, then remove the `missingSecretsFromDatadog` tag and set `activated: true` to re-enable these checks.');
    lines.push('');
  }

  // Check-Level Secrets Requiring Manual Values (D-06)
  if (report.checkLevelSecrets && report.checkLevelSecrets.totalEntries > 0) {
    const cls = report.checkLevelSecrets;
    lines.push('## Check-Level Secrets Requiring Manual Values');
    lines.push('');
    lines.push(`**${cls.totalEntries} secret(s)** across **${cls.uniqueChecks} check(s)** were migrated from Datadog \`configVariables\` with \`secure: true\`.`);
    lines.push('These need values filled in within the generated \`.check.ts\` files or via \`variables/secrets.json\` \`checkLevel\` entries.');
    lines.push('');
    lines.push('| Check | Secret Key |');
    lines.push('|-------|------------|');
    const display = cls.entries.slice(0, 25);
    for (const entry of display) {
      lines.push(`| ${entry.checkName} | \`${entry.key}\` |`);
    }
    if (cls.entries.length > 25) {
      lines.push(`| ... | ${cls.entries.length - 25} more (see secrets.json checkLevel) |`);
    }
    lines.push('');
    lines.push('> **Action:** Fill in secret values in `variables/secrets.json` under the `checkLevel` section. The operator opens one file to see all secrets needing values.');
    lines.push('');
  }

  // Checks Requiring Client Certificates (mTLS)
  if (report.clientCertificates && report.clientCertificates.totalChecks > 0) {
    const cc = report.clientCertificates;
    lines.push('## Checks Requiring Client Certificates (mTLS)');
    lines.push('');
    lines.push(`**${cc.totalChecks} check(s)** require client certificates for mutual TLS authentication.`);
    lines.push(`These checks are tagged with \`requiresClientCertificate\` and set to \`activated: false\`.`);
    lines.push('');
    lines.push('| Check | Type | Key File | Cert File |');
    lines.push('|-------|------|----------|-----------|');
    const display = cc.checks.slice(0, 25);
    for (const c of display) {
      lines.push(`| ${c.checkName} | ${c.checkType} | \`${c.certFiles.key || 'N/A'}\` | \`${c.certFiles.cert || 'N/A'}\` |`);
    }
    if (cc.checks.length > 25) {
      lines.push(`| ... | | | ${cc.checks.length - 25} more (see migration-report.json) |`);
    }
    lines.push('');
    lines.push('> **Action:** Upload your client certificate key and cert files to Checkly and configure them on each affected check. Then remove the `requiresClientCertificate` tag and set `activated: true` to enable these checks.');
    lines.push('');
  }

  // Action Required
  lines.push('---');
  lines.push('');
  lines.push('## Action Required');
  lines.push('');

  // Private locations
  if (report.privateLocations.count > 0) {
    lines.push(`### 1. Create Private Locations in Checkly (${report.privateLocations.count} locations)`);
    lines.push('');
    lines.push('Create these private locations in Checkly with the **exact slugs** shown below.');
    lines.push('The generated checks already reference these slugs.');
    lines.push('');
    lines.push('| Checkly Slug (to create) | Checks Using It | Original Datadog ID |');
    lines.push('|--------------------------|-----------------|---------------------|');
    for (const loc of report.privateLocations.locations) {
      const truncatedId = loc.datadogId.length > 50
        ? loc.datadogId.substring(0, 47) + '...'
        : loc.datadogId;
      lines.push(`| \`${loc.checklySlug}\` | ${loc.usageCount} | ${truncatedId} |`);
    }
    lines.push('');
  }

  // Secret variables
  if (report.variables.secureNeedingValues > 0) {
    lines.push(`### 2. Fill in Secret Values (${report.variables.secureNeedingValues} variables)`);
    lines.push('');
    lines.push('Secure variables were exported without values (Datadog does not expose them).');
    lines.push('');
    lines.push(`**Edit:** \`${CHECKLY_DIR}/variables/secrets.json\``);
    lines.push('');

    // Show secrets with usage counts, sorted by priority (most used first)
    const secretsWithUsage = report.variables.secretKeys.map(key => ({
      key,
      usageCount: report.variables.usage.byVariable[key]?.usageCount || 0,
    })).sort((a, b) => b.usageCount - a.usageCount);

    const usedSecrets = secretsWithUsage.filter(s => s.usageCount > 0);
    const unusedSecrets = secretsWithUsage.filter(s => s.usageCount === 0);

    if (usedSecrets.length > 0) {
      lines.push('**Priority secrets** (used by checks - fill these first):');
      lines.push('');
      lines.push('| Variable | Checks Using It |');
      lines.push('|----------|-----------------|');
      // Show top 15 used secrets
      const displayUsedSecrets = usedSecrets.slice(0, 15);
      for (const secret of displayUsedSecrets) {
        lines.push(`| \`${secret.key}\` | ${secret.usageCount} |`);
      }
      if (usedSecrets.length > 15) {
        lines.push(`| ... | ${usedSecrets.length - 15} more in secrets.json |`);
      }
      lines.push('');
    }

    if (unusedSecrets.length > 0) {
      lines.push(`**Unused secrets** (${unusedSecrets.length} variables not referenced by any check):`);
      lines.push('');
      // Show first 5 unused, then summarize
      const displayUnused = unusedSecrets.slice(0, 5);
      for (const secret of displayUnused) {
        lines.push(`- \`${secret.key}\``);
      }
      if (unusedSecrets.length > 5) {
        lines.push(`- ... and ${unusedSecrets.length - 5} more`);
      }
      lines.push('');
      lines.push('> These may be legacy variables or used by tests that were not converted.');
      lines.push('');
    }
  }

  // Next steps
  lines.push('### 3. Import Variables to Checkly');
  lines.push('');
  lines.push(`After filling in secret values, run from \`${CHECKLY_DIR}/\`:`);
  lines.push('');
  lines.push('```bash');
  lines.push('npm run create-variables');
  lines.push('```');
  lines.push('');

  lines.push('### 4. Configure Alert Channels');
  lines.push('');
  lines.push(`**Edit:** \`${CHECKLY_DIR}/default_resources/alertChannels.ts\``);
  lines.push('');
  lines.push('Configure your alert channels (Email, Slack, PagerDuty, etc.) before deployment.');
  lines.push('');

  lines.push('### 5. Test the Migration');
  lines.push('');
  lines.push(`Run from \`${CHECKLY_DIR}/\`:`);
  lines.push('');
  lines.push('```bash');
  lines.push('# Test public location checks');
  lines.push('npm run test:public');
  lines.push('');
  lines.push('# Test private location checks (after creating private locations)');
  lines.push('npm run test:private');
  lines.push('```');
  lines.push('');

  lines.push('### 6. Deploy to Checkly');
  lines.push('');
  lines.push(`Run from \`${CHECKLY_DIR}/\`:`);
  lines.push('');
  lines.push('```bash');
  lines.push('# Deploy public checks first');
  lines.push('npm run deploy:public');
  lines.push('');
  lines.push('# Deploy private checks after creating private locations');
  lines.push('npm run deploy:private');
  lines.push('```');
  lines.push('');

  lines.push('### 7. Backfill Checkly UUIDs');
  lines.push('');
  lines.push('After deploying, populate the `checkly_uuid` column in `migration-mapping.csv`:');
  lines.push('');
  lines.push('```bash');
  lines.push('npm run update-mapping');
  lines.push('```');
  lines.push('');
  lines.push('This matches deployed checks by their `migration_check_id` tag and writes the Checkly UUID into the CSV for downstream tooling and dashboards.');
  lines.push('');

  // Variable Usage Summary
  if (report.variables.usage.totalReferenced > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Environment Variable Usage');
    lines.push('');
    lines.push(`**${report.variables.usage.totalReferenced} unique variables** are referenced across all checks.`);
    lines.push('');

    // Sort all variables by usage count
    const allVarsWithUsage = Object.entries(report.variables.usage.byVariable)
      .map(([key, usage]) => ({ key, ...usage }))
      .sort((a, b) => b.usageCount - a.usageCount);

    if (allVarsWithUsage.length > 0) {
      lines.push('### Most Used Variables');
      lines.push('');
      lines.push('| Variable | Checks | Example Checks |');
      lines.push('|----------|--------|----------------|');

      // Show top 10 most used
      const topVars = allVarsWithUsage.slice(0, 10);
      for (const v of topVars) {
        const exampleChecks = v.checks.slice(0, 2).join(', ');
        const moreCount = v.checks.length > 2 ? ` (+${v.checks.length - 2} more)` : '';
        lines.push(`| \`${v.key}\` | ${v.usageCount} | ${exampleChecks}${moreCount} |`);
      }
      lines.push('');

      if (allVarsWithUsage.length > 10) {
        lines.push(`> See \`${CHECKLY_DIR}/exports/variable-usage.json\` for complete usage details.`);
        lines.push('');
      }
    }
  }

  // Notes
  lines.push('---');
  lines.push('');
  lines.push('## Notes');
  lines.push('');
  lines.push('### Conversion Notes');
  lines.push('- Browser test element locators may need manual review for accuracy');
  lines.push('- Multi-step test variable extraction between steps may need adjustment');
  lines.push('- Check groups are created but set to `activated: false` by default');
  lines.push('- Individual checks preserve their Datadog status: `paused` monitors become `activated: false`');
  lines.push('- Redirect and TLS options are migrated only when they diverge from the Datadog defaults: `follow_redirects: false` becomes `followRedirects: false`, `allow_insecure: true` becomes `skipSSL: true`, and browser `ignoreServerCertificateError: true` becomes `ignoreHTTPSErrors: true`. Absent fields are omitted because the Checkly defaults (follow redirects, verify TLS) match the Datadog defaults, so omission preserves the original behavior.');
  lines.push('- A validating partner with live Datadog access should verify the explicit false-redirect and skip-TLS cases (the ones that emit `followRedirects: false` or `skipSSL: true`), since the captured export did not exercise them.');
  lines.push('');
  lines.push('### Unsupported Features');
  lines.push('The following Datadog features cannot be automatically migrated:');
  lines.push('');
  lines.push('| Feature | Reason |');
  lines.push('|---------|--------|');
  lines.push('| SSL/ICMP tests | Checkly does not yet have direct equivalents (TCP and DNS are supported as of 2026 via TcpMonitor / DnsMonitor) |');
  lines.push('| OPTIONS HTTP method | Checkly supports: GET, POST, PUT, HEAD, DELETE, PATCH |');
  lines.push('| JavaScript assertions | Custom JS assertions must be manually converted to Playwright |');
  lines.push('| Multi-step wait steps | Steps with `subtype: wait` are not supported |');
  lines.push('');

  return lines.join('\n');
}

/**
 * Escape a CSV field value. Wraps in double quotes if the value contains
 * commas, double quotes, or newlines. Internal double quotes are doubled.
 */
export function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/**
 * Generate migration-mapping.csv with Datadog-to-Checkly ID mapping.
 *
 * Columns: datadog_public_id, datadog_name, checkly_logical_id, checkly_uuid, check_type,
 *          location_type, dd_locations, checkly_locations, filename
 *
 * checkly_uuid is always FILL_AFTER_DEPLOY — run `npm run update-mapping` post-deploy to backfill.
 * dd_locations: semicolon-separated original Datadog location strings.
 * checkly_locations: semicolon-separated Checkly public + private location slugs.
 */
export function generateMappingCsv(
  apiChecks: ApiChecksFile | null,
  multiStepTests: MultiStepTestsFile | null,
  browserTests: BrowserTestsFile | null,
  apiTestsRaw: RawApiTestsFile | null,
  tcpFilenamesOnDisk: Set<string>,
  dnsFilenamesOnDisk: Set<string>,
): string {
  const rows: string[] = [
    'datadog_public_id,datadog_name,checkly_logical_id,checkly_uuid,check_type,location_type,dd_locations,checkly_locations,filename',
  ];

  // API checks
  if (apiChecks?.checks) {
    for (const check of apiChecks.checks) {
      if (check._conversionError) continue;
      const publicId = check.logicalId; // In API checks JSON, logicalId IS the Datadog public_id
      const checklyId = uniqueLogicalId('api', check.name, publicId);
      const filename = `${sanitizeFilename(check.name, publicId)}.check.ts`;
      const locationType = check.privateLocations && check.privateLocations.length > 0 ? 'private' : 'public';
      const ddLocs = csvEscape((check.originalLocations || []).join(';'));
      const checklyLocs = csvEscape([...(check.locations || []), ...(check.privateLocations || [])].join(';'));
      rows.push(`${publicId},${csvEscape(check.name)},${checklyId},FILL_AFTER_DEPLOY,api,${locationType},${ddLocs},${checklyLocs},${filename}`);
    }
  }

  // Multi-step tests
  if (multiStepTests?.tests) {
    for (const test of multiStepTests.tests) {
      const checklyId = uniqueLogicalId('multi', test.name, test.public_id);
      const filename = `${sanitizeFilename(test.name, test.public_id)}.check.ts`;
      const locationType = test.privateLocations && test.privateLocations.length > 0 ? 'private' : 'public';
      const ddLocs = csvEscape((test.originalLocations || []).join(';'));
      const checklyLocs = csvEscape([...(test.locations || []), ...(test.privateLocations || [])].join(';'));
      rows.push(`${test.public_id},${csvEscape(test.name)},${checklyId},FILL_AFTER_DEPLOY,multistep,${locationType},${ddLocs},${checklyLocs},${filename}`);
    }
  }

  // Browser tests
  if (browserTests?.tests) {
    for (const test of browserTests.tests) {
      const checklyId = uniqueLogicalId('browser', test.name, test.public_id);
      const filename = `${sanitizeFilename(test.name, test.public_id)}.check.ts`;
      const locationType = test.privateLocations && test.privateLocations.length > 0 ? 'private' : 'public';
      const ddLocs = csvEscape((test.originalLocations || []).join(';'));
      const checklyLocs = csvEscape([...(test.locations || []), ...(test.privateLocations || [])].join(';'));
      rows.push(`${test.public_id},${csvEscape(test.name)},${checklyId},FILL_AFTER_DEPLOY,browser,${locationType},${ddLocs},${checklyLocs},${filename}`);
    }
  }

  // TCP monitors (Datadog subtype:'tcp' → Checkly TcpMonitor via step 04b).
  // Only emit rows for TCP files that actually exist in this project's
  // __checks__/tcp/ — when CHECKLY_TCP_PROJECT_NAME is used to split TCP into a
  // sibling project, this project should not claim those monitors.
  if (apiTestsRaw?.tests) {
    for (const test of apiTestsRaw.tests) {
      if (test.subtype !== 'tcp') continue;
      const filename = `${sanitizeFilename(test.name, test.public_id)}.check.ts`;
      if (!tcpFilenamesOnDisk.has(filename)) continue;
      const checklyId = uniqueLogicalId('tcp', test.name, test.public_id);
      const locationType = test.privateLocations && test.privateLocations.length > 0 ? 'private' : 'public';
      const ddLocs = csvEscape((test.originalLocations || []).join(';'));
      const checklyLocs = csvEscape([...(test.locations || []), ...(test.privateLocations || [])].join(';'));
      rows.push(`${test.public_id},${csvEscape(test.name)},${checklyId},FILL_AFTER_DEPLOY,tcp,${locationType},${ddLocs},${checklyLocs},${filename}`);
    }
  }

  // DNS monitors (Datadog subtype:'dns' → Checkly DnsMonitor via step 04c).
  // Same on-disk gate as TCP — CHECKLY_DNS_PROJECT_NAME splits DNS to a sibling project.
  if (apiTestsRaw?.tests) {
    for (const test of apiTestsRaw.tests) {
      if (test.subtype !== 'dns') continue;
      const filename = `${sanitizeFilename(test.name, test.public_id)}.check.ts`;
      if (!dnsFilenamesOnDisk.has(filename)) continue;
      const checklyId = uniqueLogicalId('dns', test.name, test.public_id);
      const locationType = test.privateLocations && test.privateLocations.length > 0 ? 'private' : 'public';
      const ddLocs = csvEscape((test.originalLocations || []).join(';'));
      const checklyLocs = csvEscape([...(test.locations || []), ...(test.privateLocations || [])].join(';'));
      rows.push(`${test.public_id},${csvEscape(test.name)},${checklyId},FILL_AFTER_DEPLOY,dns,${locationType},${ddLocs},${checklyLocs},${filename}`);
    }
  }

  return rows.join('\n') + '\n';
}

/**
 * Main function
 */
async function main(): Promise<void> {
  CHECKLY_DIR = await getOutputRoot();
  EXPORTS_DIR = await getExportsDir();
  OUTPUT_JSON = path.join(CHECKLY_DIR, 'migration-report.json');
  OUTPUT_MD = path.join(CHECKLY_DIR, 'migration-report.md');
  OUTPUT_CSV = path.join(CHECKLY_DIR, 'migration-mapping.csv');
  FILES = {
    exportSummary: path.join(EXPORTS_DIR, 'export-summary.json'),
    privateLocations: path.join(EXPORTS_DIR, 'private-locations.json'),
    apiTests: path.join(EXPORTS_DIR, 'api-tests.json'),
    apiChecks: path.join(EXPORTS_DIR, 'checkly-api-checks.json'),
    multiStepTests: path.join(EXPORTS_DIR, 'multi-step-tests.json'),
    browserTests: path.join(EXPORTS_DIR, 'browser-tests.json'),
    envVariables: path.join(CHECKLY_DIR, 'variables', 'env-variables.json'),
    secrets: path.join(CHECKLY_DIR, 'variables', 'secrets.json'),
    variableUsage: path.join(EXPORTS_DIR, 'variable-usage.json'),
    ddTestStatus: path.join(EXPORTS_DIR, 'dd-test-status.json'),
    missingSecretsReport: path.join(EXPORTS_DIR, 'missing-secrets-report.json'),
    migrationFlags: path.join(EXPORTS_DIR, 'migration-flags.json'),
    browserManifestPublic: path.join(CHECKLY_DIR, 'tests', 'browser', 'public', '_manifest.json'),
    browserManifestPrivate: path.join(CHECKLY_DIR, 'tests', 'browser', 'private', '_manifest.json'),
    multiManifestPublic: path.join(CHECKLY_DIR, 'tests', 'multi', 'public', '_manifest.json'),
    multiManifestPrivate: path.join(CHECKLY_DIR, 'tests', 'multi', 'private', '_manifest.json'),
  };

  console.log('='.repeat(60));
  console.log('Migration Report Generator');
  console.log('='.repeat(60));

  // Read all input files
  console.log('\nReading input files...');

  const exportSummary = await readJsonFile<ExportSummary>(FILES.exportSummary);
  const privateLocationsFile = await readJsonFile<PrivateLocationsFile>(FILES.privateLocations);
  const apiTestsRaw = await readJsonFile<RawApiTestsFile>(FILES.apiTests);
  const apiChecks = await readJsonFile<ApiChecksFile>(FILES.apiChecks);
  const multiStepTests = await readJsonFile<MultiStepTestsFile>(FILES.multiStepTests);
  const browserTests = await readJsonFile<BrowserTestsFile>(FILES.browserTests);
  const envVariables = await readJsonFile<Variable[]>(FILES.envVariables);
  const secretsRaw = await readJsonFile<Variable[] | { global: Variable[]; checkLevel: Array<{ checkName: string; key: string; value: string; locked: boolean }> }>(FILES.secrets);
  // Normalize: extract global secrets for backward compat
  const secrets = secretsRaw ? (Array.isArray(secretsRaw) ? secretsRaw : secretsRaw.global || []) : null;
  const checkLevelSecrets = secretsRaw && !Array.isArray(secretsRaw) ? secretsRaw.checkLevel || [] : [];
  const variableUsage = await readJsonFile<VariableUsageFile>(FILES.variableUsage);
  const browserManifestPublic = await readJsonFile<Manifest>(FILES.browserManifestPublic);
  const browserManifestPrivate = await readJsonFile<Manifest>(FILES.browserManifestPrivate);
  const multiManifestPublic = await readJsonFile<Manifest>(FILES.multiManifestPublic);
  const multiManifestPrivate = await readJsonFile<Manifest>(FILES.multiManifestPrivate);
  const ddTestStatus = await readJsonFile<DdTestStatusFile>(FILES.ddTestStatus);
  const missingSecretsReport = await readJsonFile<MissingSecretsReportFile>(FILES.missingSecretsReport);
  const migrationFlagsFile = await readJsonFile<MigrationFlagsFile>(FILES.migrationFlags);

  if (!exportSummary) {
    console.error('\nError: export-summary.json not found. Run the export first.');
    process.exit(1);
  }

  console.log('  - export-summary.json: found');
  console.log(`  - private-locations.json: ${privateLocationsFile ? 'found' : 'not found'}`);
  console.log(`  - api-tests.json: ${apiTestsRaw ? 'found' : 'not found'}`);
  console.log(`  - checkly-api-checks.json: ${apiChecks ? 'found' : 'not found'}`);
  console.log(`  - multi-step-tests.json: ${multiStepTests ? 'found' : 'not found'}`);
  console.log(`  - browser-tests.json: ${browserTests ? 'found' : 'not found'}`);
  console.log(`  - env-variables.json: ${envVariables ? 'found' : 'not found'}`);
  console.log(`  - secrets.json: ${secrets ? 'found' : 'not found'}`);
  console.log(`  - variable-usage.json: ${variableUsage ? 'found' : 'not found'}`);
  console.log(`  - dd-test-status.json: ${ddTestStatus ? 'found' : 'not found'}`);
  console.log(`  - missing-secrets-report.json: ${missingSecretsReport ? 'found' : 'not found'}`);
  console.log(`  - migration-flags.json: ${migrationFlagsFile ? 'found' : 'not found'}`);

  // Calculate counts
  const apiPublicCount = apiChecks?.checks.filter(c =>
    !c._conversionError && (!c.privateLocations || c.privateLocations.length === 0)
  ).length || 0;
  const apiPrivateCount = apiChecks?.checks.filter(c =>
    !c._conversionError && c.privateLocations && c.privateLocations.length > 0
  ).length || 0;

  const browserPublicCount = browserManifestPublic?.files.length || 0;
  const browserPrivateCount = browserManifestPrivate?.files.length || 0;

  const multiPublicCount = multiManifestPublic?.files.length || 0;
  const multiPrivateCount = multiManifestPrivate?.files.length || 0;

  // Count TCP monitors actually present in this project's __checks__/tcp/ directory.
  // We count from disk (not from api-tests.json) because TCP can be split into a
  // standalone project via CHECKLY_TCP_PROJECT_NAME — in which case this project
  // should report 0 TCP, even though api-tests.json still lists the source tests.
  const countTcpFilesIn = async (dir: string): Promise<number> => {
    if (!existsSync(dir)) return 0;
    const entries = await readdir(dir);
    return entries.filter(f => f.endsWith('.check.ts')).length;
  };
  const tcpPublicCount = await countTcpFilesIn(path.join(CHECKLY_DIR, '__checks__', 'tcp', 'public'));
  const tcpPrivateCount = await countTcpFilesIn(path.join(CHECKLY_DIR, '__checks__', 'tcp', 'private'));
  const dnsPublicCount = await countTcpFilesIn(path.join(CHECKLY_DIR, '__checks__', 'dns', 'public'));
  const dnsPrivateCount = await countTcpFilesIn(path.join(CHECKLY_DIR, '__checks__', 'dns', 'private'));
  // Track which DD publicIds have a corresponding TCP/DNS .check.ts file on disk,
  // so the mapping CSV only emits rows for actually-generated monitors.
  const tcpFilenamesOnDisk = new Set<string>();
  for (const dir of [
    path.join(CHECKLY_DIR, '__checks__', 'tcp', 'public'),
    path.join(CHECKLY_DIR, '__checks__', 'tcp', 'private'),
  ]) {
    if (existsSync(dir)) {
      for (const f of await readdir(dir)) {
        if (f.endsWith('.check.ts')) tcpFilenamesOnDisk.add(f);
      }
    }
  }
  const dnsFilenamesOnDisk = new Set<string>();
  for (const dir of [
    path.join(CHECKLY_DIR, '__checks__', 'dns', 'public'),
    path.join(CHECKLY_DIR, '__checks__', 'dns', 'private'),
  ]) {
    if (existsSync(dir)) {
      for (const f of await readdir(dir)) {
        if (f.endsWith('.check.ts')) dnsFilenamesOnDisk.add(f);
      }
    }
  }

  const totalChecklyChecks =
    apiPublicCount + apiPrivateCount +
    browserPublicCount + browserPrivateCount +
    multiPublicCount + multiPrivateCount +
    tcpPublicCount + tcpPrivateCount +
    dnsPublicCount + dnsPrivateCount;

  const totalDatadogTests = exportSummary.summary.apiTests + exportSummary.summary.browserTests;

  // Collect non-HTTP tests with names, grouped by type
  const nonHttpByType: Record<string, Array<{ publicId: string; name: string }>> = {};
  if (apiChecks?.skippedNonHttpTests) {
    for (const [type, tests] of Object.entries(apiChecks.skippedNonHttpTests)) {
      nonHttpByType[type] = tests.map(t => ({ publicId: t.public_id, name: t.name }));
    }
  }
  const nonHttpTotal = Object.values(nonHttpByType).reduce((sum, tests) => sum + tests.length, 0);

  // Collect failed conversions with names and reasons
  const failedChecks = apiChecks?.checks.filter(c => c._conversionError) || [];
  const failedTests: Array<{ publicId: string; name: string; reason: string }> = [];
  for (const check of failedChecks) {
    const error = check._conversionError || 'Unknown error';
    let reason: string;
    if (error.includes('Unsupported HTTP method')) {
      const methodMatch = error.match(/method: (\w+)/);
      reason = methodMatch ? `Unsupported HTTP method: ${methodMatch[1]}` : 'Unsupported HTTP method';
    } else if (error.includes('JavaScript')) {
      reason = 'JavaScript assertions not supported';
    } else {
      reason = error.length > 60 ? error.substring(0, 57) + '...' : error;
    }
    failedTests.push({ publicId: check.logicalId, name: check.name, reason });
  }

  // Collect skipped tests from manifests (multi-step and browser)
  const skippedFromManifests: Array<{ publicId: string; name: string; reason: string }> = [];
  const manifests = [browserManifestPublic, browserManifestPrivate, multiManifestPublic, multiManifestPrivate];
  for (const manifest of manifests) {
    if (manifest?.skipped) {
      for (const s of manifest.skipped) {
        skippedFromManifests.push({
          publicId: s.logicalId,
          name: s.name,
          reason: s.reason || 'Incompatible step types',
        });
      }
    }
  }

  // Collect checks requiring client certificates (mTLS)
  const certChecks: Array<{
    checkName: string;
    checkType: 'api' | 'multistep';
    publicId: string;
    certFiles: { key?: string; cert?: string };
  }> = [];

  // From API checks
  if (apiChecks?.checks) {
    for (const check of apiChecks.checks) {
      if (check.hasCertificate || check.tags?.includes('requiresClientCertificate')) {
        certChecks.push({
          checkName: check.name,
          checkType: 'api',
          publicId: check.logicalId,
          certFiles: {
            key: check.request?.certificate?.key?.filename,
            cert: check.request?.certificate?.cert?.filename,
          },
        });
      }
    }
  }

  // From multi-step tests
  if (multiStepTests?.tests) {
    for (const test of multiStepTests.tests) {
      if (test.hasCertificate || test.tags?.includes('requiresClientCertificate')) {
        const keyFiles: string[] = [];
        const certFileNames: string[] = [];
        for (const step of (test.config?.steps || [])) {
          if (step.request?.certificate?.key?.filename && !keyFiles.includes(step.request.certificate.key.filename)) {
            keyFiles.push(step.request.certificate.key.filename);
          }
          if (step.request?.certificate?.cert?.filename && !certFileNames.includes(step.request.certificate.cert.filename)) {
            certFileNames.push(step.request.certificate.cert.filename);
          }
        }
        certChecks.push({
          checkName: test.name,
          checkType: 'multistep',
          publicId: test.public_id,
          certFiles: {
            key: keyFiles.join(', ') || undefined,
            cert: certFileNames.join(', ') || undefined,
          },
        });
      }
    }
  }

  // Promoted checks (REGX-09): sourced only from the _promotionReason field on
  // multi-step-tests.json, never by re-scanning generated .check.ts files.
  const promotions = (multiStepTests?.tests || [])
    .filter(t => Boolean(t._promotionReason))
    .map(t => ({
      publicId: t.public_id,
      name: t.name,
      reason: t._promotionReason as string,
      locationType: (t.privateLocations && t.privateLocations.length > 0 ? 'private' : 'public') as 'public' | 'private',
    }));

  // Migration flags (FLAG-03): sourced only from exports/migration-flags.json,
  // never by re-scanning generated .spec.ts files. Null-tolerant: an absent file
  // (readJsonFile returns null) or an absent flags member yields an empty array,
  // so step 12 completes and renders no section when there are no flags.
  const migrationFlags = migrationFlagsFile?.flags || [];

  // Self-healing locator chains (D-06): derive the multi-candidate review list
  // from the already-loaded browser manifests' hasMultiCandidate field. Null-
  // tolerant for manifests predating the field. Public and private are merged;
  // each check records its location type from which manifest it came from.
  const multiSelectorChecks: Array<{ publicId: string; name: string; locationType: 'public' | 'private' }> = [];
  for (const file of browserManifestPublic?.files || []) {
    if (file.hasMultiCandidate) {
      multiSelectorChecks.push({ publicId: file.logicalId, name: file.name, locationType: 'public' });
    }
  }
  for (const file of browserManifestPrivate?.files || []) {
    if (file.hasMultiCandidate) {
      multiSelectorChecks.push({ publicId: file.logicalId, name: file.name, locationType: 'private' });
    }
  }

  // Playwright Check Suites (PWCS-03): derive the multi-engine review list from the
  // already-loaded browser manifests' pwEngines field, mirroring the multiSelector
  // loop above (file.logicalId is the Datadog public_id; src/07 writes it). A file
  // whose pwEngines has length > 1 was emitted as a PlaywrightCheck by src/08.
  // The manifest carries only the deduped engine list, so declaredBrowserCount and
  // hasPrivateLocationCaveat cross-reference the already-loaded browserTests by
  // public_id: options.device_ids length for the declared count (falling back to
  // the engine count so the field is never undefined) and any privateLocations for
  // the D-07 Agent-version caveat.
  const playwrightCheckSuiteEntries: Array<{
    publicId: string;
    name: string;
    locationType: 'public' | 'private';
    declaredBrowserCount: number;
    distinctEngineCount: number;
    hasPrivateLocationCaveat: boolean;
  }> = [];
  const derivePwcsEntry = (
    file: { logicalId: string; name: string; pwEngines?: string[] },
    locationType: 'public' | 'private',
  ) => {
    const engines = file.pwEngines || [];
    if (engines.length <= 1) return;
    const test = browserTests?.tests.find(t => t.public_id === file.logicalId);
    const deviceCount = test?.options?.device_ids?.length ?? 0;
    playwrightCheckSuiteEntries.push({
      publicId: file.logicalId,
      name: file.name,
      locationType,
      declaredBrowserCount: deviceCount > 0 ? deviceCount : engines.length,
      distinctEngineCount: engines.length,
      hasPrivateLocationCaveat: (test?.privateLocations?.length ?? 0) > 0,
    });
  };
  for (const file of browserManifestPublic?.files || []) derivePwcsEntry(file, 'public');
  for (const file of browserManifestPrivate?.files || []) derivePwcsEntry(file, 'private');

  // Build the report
  const report: MigrationReport = {
    generatedAt: new Date().toISOString(),
    source: {
      exportedAt: exportSummary.exportedAt,
      site: exportSummary.site,
    },
    summary: {
      totalDatadogTests,
      totalChecklyChecks,
      conversionRate: totalDatadogTests > 0
        ? `${Math.round((totalChecklyChecks / totalDatadogTests) * 100)}%`
        : '0%',
    },
    converted: {
      apiChecks: {
        public: apiPublicCount,
        private: apiPrivateCount,
        total: apiPublicCount + apiPrivateCount,
      },
      browserChecks: {
        public: browserPublicCount,
        private: browserPrivateCount,
        total: browserPublicCount + browserPrivateCount,
      },
      multiStepChecks: {
        public: multiPublicCount,
        private: multiPrivateCount,
        total: multiPublicCount + multiPrivateCount,
      },
      tcpMonitors: {
        public: tcpPublicCount,
        private: tcpPrivateCount,
        total: tcpPublicCount + tcpPrivateCount,
      },
      dnsMonitors: {
        public: dnsPublicCount,
        private: dnsPrivateCount,
        total: dnsPublicCount + dnsPrivateCount,
      },
    },
    notConverted: {
      nonHttpTests: {
        count: nonHttpTotal,
        byType: nonHttpByType,
      },
      failedConversions: {
        count: failedTests.length,
        tests: failedTests,
      },
      skippedFromManifests,
    },
    variables: {
      total: (envVariables?.length || 0) + (secrets?.length || 0),
      nonSecure: envVariables?.length || 0,
      secureNeedingValues: secrets?.length || 0,
      secretKeys: secrets?.map(s => s.key) || [],
      usage: {
        totalReferenced: variableUsage?.totalVariablesReferenced || 0,
        byVariable: variableUsage?.variables || {},
      },
    },
    privateLocations: {
      count: privateLocationsFile?.locations.length || 0,
      locations: (privateLocationsFile?.locations || []).map(loc => ({
        checklySlug: loc.checklySlug,
        usageCount: loc.usageCount,
        datadogId: loc.datadogId,
      })),
    },
    datadogStatus: ddTestStatus ? {
      checkedAt: ddTestStatus.fetchedAt,
      summary: ddTestStatus.summary,
      publicSummary: ddTestStatus.publicSummary,
      privateSummary: ddTestStatus.privateSummary,
      ...projectDatadogStatusTests(ddTestStatus.tests),
    } : undefined,
    missingSecrets: missingSecretsReport && missingSecretsReport.checksAffected > 0 ? {
      checkedAt: missingSecretsReport.generatedAt,
      checksAffected: missingSecretsReport.checksAffected,
      filesModified: missingSecretsReport.filesModified,
      affectedChecks: missingSecretsReport.affectedChecks,
    } : undefined,
    checkLevelSecrets: checkLevelSecrets.length > 0 ? {
      totalEntries: checkLevelSecrets.length,
      uniqueChecks: new Set(checkLevelSecrets.map(s => s.checkName)).size,
      entries: checkLevelSecrets.map(s => ({ checkName: s.checkName, key: s.key })),
    } : undefined,
    clientCertificates: certChecks.length > 0 ? {
      totalChecks: certChecks.length,
      checks: certChecks,
    } : undefined,
    promotions: promotions.length > 0 ? promotions : undefined,
    migrationFlags: migrationFlags.length > 0 ? migrationFlags : undefined,
    multiSelector: multiSelectorChecks.length > 0
      ? { count: multiSelectorChecks.length, checks: multiSelectorChecks }
      : undefined,
    playwrightCheckSuites: playwrightCheckSuiteEntries.length > 0
      ? { count: playwrightCheckSuiteEntries.length, checks: playwrightCheckSuiteEntries }
      : undefined,
    nextSteps: [
      privateLocationsFile && privateLocationsFile.locations.length > 0
        ? `Create ${privateLocationsFile.locations.length} private location(s) in Checkly with the slugs shown in the report`
        : null,
      secrets && secrets.length > 0
        ? `Fill in values for ${secrets.length} secret variable(s) in ${CHECKLY_DIR}/variables/secrets.json`
        : null,
      ddTestStatus && ddTestStatus.summary.deactivated > 0
        ? `Review ${ddTestStatus.summary.deactivated} deactivated check(s) tagged "failingInDatadog", "noDataInDatadog", or "reviewNoDataInDatadog"`
        : null,
      missingSecretsReport && missingSecretsReport.checksAffected > 0
        ? `Fill in secret values in ${CHECKLY_DIR}/variables/secrets.json and remove "missingSecretsFromDatadog" tag from ${missingSecretsReport.checksAffected} deactivated check(s)`
        : null,
      checkLevelSecrets.length > 0
        ? `Fill in values for ${checkLevelSecrets.length} check-level secret(s) in ${CHECKLY_DIR}/variables/secrets.json under the "checkLevel" section`
        : null,
      certChecks.length > 0
        ? `Upload client certificates for ${certChecks.length} check(s) tagged "requiresClientCertificate", configure mTLS on each check, then remove the tag and set activated: true`
        : null,
      migrationFlags.length > 0
        ? `Review ${migrationFlags.length} migration flag(s) in the "Migration Flags" report section (grep "// MIGRATION-FLAG:" in generated specs), then remove the "reviewMigrationFlag" tag and re-activate any deactivated checks`
        : null,
      multiSelectorChecks.length > 0
        ? `Verify ${multiSelectorChecks.length} check(s) tagged "reviewMultiSelector" in the "Self-Healing Locator Chains" report section (grep "${LOCATOR_EXHAUSTION_TOKEN}" in run logs when a chain misses), then remove the tag once the resolved element is confirmed`
        : null,
      `Review checks tagged "datadogBasicAuthWeb" — these used web/form-based auth in Datadog and may need converting to browser or multi-step checks`,
      `Run "cd ${CHECKLY_DIR} && npm run create-variables" to import variables to Checkly`,
      `Configure alert channels in ${CHECKLY_DIR}/default_resources/alertChannels.ts`,
      `Run "cd ${CHECKLY_DIR} && npm run test:public" to validate public checks`,
      privateLocationsFile && privateLocationsFile.locations.length > 0
        ? `Run "cd ${CHECKLY_DIR} && npm run test:private" to validate private checks (after creating private locations)`
        : null,
      `Run "cd ${CHECKLY_DIR} && npm run deploy:public" to deploy public checks`,
      privateLocationsFile && privateLocationsFile.locations.length > 0
        ? `Run "cd ${CHECKLY_DIR} && npm run deploy:private" to deploy private checks`
        : null,
    ].filter((step): step is string => step !== null),
  };

  // Generate outputs
  console.log('\nGenerating reports...');

  // JSON report
  await writeFile(OUTPUT_JSON, JSON.stringify(report, null, 2), 'utf-8');
  console.log(`  Written: ${OUTPUT_JSON}`);

  // Markdown report
  const markdown = generateMarkdownReport(report);
  await writeFile(OUTPUT_MD, markdown, 'utf-8');
  console.log(`  Written: ${OUTPUT_MD}`);

  // CSV mapping
  const csv = generateMappingCsv(apiChecks, multiStepTests, browserTests, apiTestsRaw, tcpFilenamesOnDisk, dnsFilenamesOnDisk);
  await writeFile(OUTPUT_CSV, csv, 'utf-8');
  console.log(`  Written: ${OUTPUT_CSV}`);

  // Print summary
  console.log('\n' + '='.repeat(60));
  console.log('Migration Report Summary');
  console.log('='.repeat(60));
  console.log(`  Datadog tests: ${report.summary.totalDatadogTests}`);
  console.log(`  Checkly checks: ${report.summary.totalChecklyChecks}`);
  console.log(`  Conversion rate: ${report.summary.conversionRate}`);
  console.log(`  Private locations to create: ${report.privateLocations.count}`);
  console.log(`  Secrets needing values: ${report.variables.secureNeedingValues}`);
  console.log(`  Variables referenced in checks: ${report.variables.usage.totalReferenced}`);

  if (report.notConverted.nonHttpTests.count > 0) {
    console.log(`  Non-HTTP tests skipped: ${report.notConverted.nonHttpTests.count}`);
  }

  if (report.datadogStatus) {
    console.log(`  Datadog tests failing: ${report.datadogStatus.summary.failing}`);
    console.log(`  Datadog tests no data: ${report.datadogStatus.summary.noData}`);
    console.log(`  Total checks deactivated: ${report.datadogStatus.deactivatedTests.length}`);
  }

  if (report.missingSecrets) {
    console.log(`  Checks deactivated (missing secrets): ${report.missingSecrets.checksAffected}`);
  }

  if (report.checkLevelSecrets) {
    console.log(`  Check-level secrets: ${report.checkLevelSecrets.totalEntries} across ${report.checkLevelSecrets.uniqueChecks} check(s)`);
  }

  if (certChecks.length > 0) {
    console.log(`  Client certificate checks: ${certChecks.length}`);
  }

  console.log('\nView the full report:');
  console.log(`  - ${OUTPUT_MD} (human-readable)`);
  console.log(`  - ${OUTPUT_JSON} (machine-readable)`);
  console.log(`  - ${OUTPUT_CSV} (ID mapping)`);

  console.log('\nDone!');
}

// ESM main-guard: only run if this file is the direct entry point
const __filename = fileURLToPath(import.meta.url);
if (typeof process.argv[1] === 'string' && path.resolve(__filename) === path.resolve(process.argv[1])) {
  main().catch(err => {
    console.error('Error:', (err as Error).message);
    process.exit(1);
  });
}
